### PR TITLE
peerDependencies less strict

### PR DESCRIPTION
**Pull request by AckerApple**
Fix being able to use updated versions of peerDependencies

### CODE REVIEW

**Comment by ramseyrashid** [comment]
Bump. We need this. Please and thank you :)

**Review by youngjoon-lee — APPROVED** [review]
Thank you. I will publish this new version 1.0.1 soon.

**Comment by AckerApple** [comment]
Wonderful. Friendly reminder to publish to npm please and thank you

**Comment by youngjoon-lee** [comment]
@AckerApple I just published the v1.0.1: https://www.npmjs.com/package/@medibloc/nestjs-request-context/v/1.0.1 
Thank you for your contribution!

**Comment by AckerApple** [comment]
Feels good to contribute. Wonder what is up with all the similar name spaces on "npm". Turned out we had this package installed into one repo and then a different context package installed in another repo of almost same name.

image

**Pull request merged**
